version: 2
jobs:
  build:

    working_directory: ~/cicd

    docker:
    - image: circleci/openjdk:8u171-jdk
      enviroment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root


    - image: circleci/postgres:9.6.5-alpine-ram
      enviroment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb

    steps:

    - checkout

    - run: mvn dependency:go-offline
    - run: mvn test

  deploy:
    docker:
    - image: buildpack-deps:trusty

    steps:
    - checkout
    - run:
        name: Wrzucam apke na heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build